// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import type { PrismaConfig } from "prisma"
import { env } from "process";
import { config } from "dotenv"
config();

export default {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: env.DATABASE_URL,
  },
} satisfies PrismaConfig;

if (!env.DATABASE_URL) {
  throw new Error("DATABASE_URL is not defined in environment variables");
}